### ISSUE TITLE
Installation via Cocoapods causes xcasset problems

### ISSUE THREAD

**Issue by weiran** [kodlian/TVVLCPlayer#3]
When I add TVVLCPlayer via Cocoapods, my tvOS app no longer recognises any of my assets in the xcasset file. This means the app icon and top shelf components are missing at runtime, even though the xcasset file and project are configured correctly. This can be fixed by removing TVVLCPlayer as a dependency.

Any ideas what could be causing this? Removing the build phase that copies pod resources had no effect.

**Comment by kodlian** [comment]
Since `TVVLCKit` is a static dependence for `TVVLCPlayer`, `TVVLCPlayer` needs to static also (a cocoa pods limitation) and by consequence doesn't have a bundle. So it seems that the xcassets from `TVVLCPlayer` is copied in your app and replace your own assets. I will rename the assets to avoid any collision but I was assuming that cocoa pods does a better job to handle this kind of thing.

**Comment by kodlian** [comment]
This should be fixed by 0c6dd8f425aa55aa4733d5e2a0a3d1099f0cb8c6
